#生产环境
spring:
  datasource:
    url: jdbc:mysql://47.95.205.133/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: hh823501629!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.huang: info
  file: log/blog-pro.log
server:
  port: 80